# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a8cec1663da7247ab776e539ae369ca8085deeb92251f7ef49c98587c992e4fad68de3276364e0295e7aacdea3ffb6d98b1e4a074db26519af9fcf20747913e

test:
  secret_key_base: 9f8cceeb1d6bd4aabf6101ea7847eb2432412c23f1af86b73ed082448f7afa4b749152c252abf4049ba2712046562269526eda5c9d914cf72076b3b38e0670d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
